<a href="https://colab.research.google.com/github/Varshitha2204/Graph-Convolutional-Neural-Network/blob/main/GCNN_74.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch-geometric


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.6/661.6 kB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for torch-geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910459 sha256=fc07c90ce0b33ba309cecf94919d8b1b16468c1a4509238c421df4869a5d5fa3
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch-geometric


In [ ]:
import csv

# Sample data as a list of lists
data = [
    ['image_path', 'incisor_width', 'intercanine_distance', 'gender'],
    ['/content/drive/MyDrive/rt/94.png', 13.7, 33, 'female'],
    ['/content/drive/MyDrive/rt/93.png', 14.8, 31.3, 'male'],
    ['/content/drive/MyDrive/rt/92.png', 15.7, 33.7, 'male'],
    ['/content/drive/MyDrive/rt/91.png', 14.4, 33, 'male'],
    ['/content/drive/MyDrive/rt/83.png', 14, 31.5, 'female'],
    ['/content/drive/MyDrive/rt/84.png', 14.1, 31, 'female'],
    ['/content/drive/MyDrive/rt/81.png', 14.7, 33.4, 'male'],
    ['/content/drive/MyDrive/rt/80.png', 15.7, 33, 'male'],
    ['/content/drive/MyDrive/rt/74.png', 14.7, 33.7, 'male'],
    ['/content/drive/MyDrive/rt/73.png', 15, 31.7, 'male'],
    ['/content/drive/MyDrive/rt/72.png', 14.3, 33.7, 'male'],
    ['/content/drive/MyDrive/rt/71.png', 14.4, 31, 'female'],
    ['/content/drive/MyDrive/rt/64.png', 14.2, 31, 'female'],
    ['/content/drive/MyDrive/rt/63.png', 12.7, 30, 'female'],
    ['/content/drive/MyDrive/rt/62.png', 12.8, 32, 'female'],
    ['/content/drive/MyDrive/rt/61.png', 14.3, 34.3, 'male'],
    ['/content/drive/MyDrive/rt/6.png', 14, 32.7, 'female'],
    ['/content/drive/MyDrive/rt/54.png', 16.1, 29, 'male'],
    ['/content/drive/MyDrive/rt/53.png', 14.1, 30.4, 'female'],
    ['/content/drive/MyDrive/rt/51.png', 15.3, 36, 'male'],
    ['/content/drive/MyDrive/rt/50.png', 14, 29, 'female'],
    ['/content/drive/MyDrive/rt/43.png', 13.7, 28, 'female'],
    ['/content/drive/MyDrive/rt/42.png', 15.7, 32.3, 'male'],
    ['/content/drive/MyDrive/rt/41.png', 13.7, 31.7, 'female'],
    ['/content/drive/MyDrive/rt/40.png', 14, 29.4, 'female'],
    ['/content/drive/MyDrive/rt/4.png', 14.3, 33.3, 'male'],
    ['/content/drive/MyDrive/rt/33.png', 14.7, 30, 'female'],
    ['/content/drive/MyDrive/rt/32.png', 15.7, 29.3, 'female'],
    ['/content/drive/MyDrive/rt/31.png', 13.7, 32, 'female'],
    ['/content/drive/MyDrive/rt/30.png', 13.4, 28.3, 'female'],
    ['/content/drive/MyDrive/rt/24.png', 12.4, 30, 'female'],
    ['/content/drive/MyDrive/rt/23.png', 14.7, 36, 'male'],
    ['/content/drive/MyDrive/rt/22.png', 14.8, 31.3, 'male'],
    ['/content/drive/MyDrive/rt/20.png', 16.7, 33, 'male'],
    ['/content/drive/MyDrive/rt/2.png', 14.7, 29.7, 'female'],
    ['/content/drive/MyDrive/rt/114.png', 13.7, 28.7, 'female'],
    ['/content/drive/MyDrive/rt/113.png', 15, 31, 'male'],
    ['/content/drive/MyDrive/rt/112.png', 16, 31.7, 'male'],
    ['/content/drive/MyDrive/rt/111.png', 14, 30.7, 'female'],
    ['/content/drive/MyDrive/rt/105.png', 13, 30, 'female'],
    ['/content/drive/MyDrive/rt/104.png', 12, 27.7, 'female'],
    ['/content/drive/MyDrive/rt/102.png', 16, 34, 'male'],
    ['/content/drive/MyDrive/rt/101.png', 13.4, 29.6, 'female'],
    # Add more rows as needed
]

# Specify the CSV file path
csv_file = '/content/drive/MyDrive/dataset.csv'

# Write data to the CSV file
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)


In [ ]:
!git clone https://github.com/rusty1s/pytorch_geometric.git


Cloning into 'pytorch_geometric'...
remote: Enumerating objects: 58705, done.
remote: Counting objects: 100% (58705/58705), done.
remote: Compressing objects: 100% (13491/13491), done.
remote: Total 58705 (delta 45633), reused 57072 (delta 44900), pack-reused 0
Receiving objects: 100% (58705/58705), 13.11 MiB | 17.93 MiB/s, done.
Resolving deltas: 100% (45633/45633), done.


In [ ]:
!pip install torch-geometric

  Using cached torch_geometric-2.3.1.tar.gz (661 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for torch-geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910459 sha256=f228cc5e23b3c6525a1b1f5442d762880b96d0618d4e370798f948fa03d1c08f
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch-geometric


In [ ]:
import pandas as pd
import numpy as np
import cv2
from skimage.feature import greycomatrix, greycoprops
from sklearn.model_selection import train_test_split

# Load the dataset from CSV
dataset = pd.read_csv('/content/drive/MyDrive/dataset.csv')

# Create empty lists to store features and labels
features = []
gender_labels = []

# Iterate over the dataset rows and extract features and labels
for index, row in dataset.iterrows():
    image_path = row['image_path']
    gender_label = row['gender']
    incisor_width = row['incisor_width']
    intercanine_distance = row['intercanine_distance']

    # Perform preprocessing and feature extraction on the image
    def preprocess_image(image_path):
        # Load the image using OpenCV
        image = cv2.imread(image_path)

        # Convert the image to grayscale
        gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Perform additional preprocessing steps if required (e.g., denoising, resizing, histogram equalization, etc.)
        # ...

        return gray_image

    def extract_features(image_path):
        # Preprocess the image
        preprocessed_image = preprocess_image(image_path)

        # Perform feature extraction using gray-level co-occurrence matrix (GLCM)
        distances = [1]  # List of distances for GLCM calculation
        angles = [0, np.pi/4, np.pi/2, 3*np.pi/4]  # List of angles for GLCM calculation
        glcm = greycomatrix(preprocessed_image, distances, angles)

        # Calculate GLCM properties (replace with the desired properties from the paper)
        contrast = greycoprops(glcm, 'contrast')
        dissimilarity = greycoprops(glcm, 'dissimilarity')
        energy = greycoprops(glcm, 'energy')
        correlation = greycoprops(glcm, 'correlation')

        # Concatenate the feature vectors
        features = np.concatenate([contrast.flatten(), dissimilarity.flatten(), energy.flatten(), correlation.flatten()])

        return features

    extracted_features = extract_features(image_path)

    # Append the extracted features and additional features to the features list
    features.append(np.concatenate([extracted_features, [incisor_width, intercanine_distance]]))

    # Append the gender label to the gender_labels list
    gender_labels.append(gender_label)

# Convert the features and gender_labels lists to NumPy arrays
features = np.array(features)
gender_labels = np.array(gender_labels)

# Split the dataset into training and testing sets
train_features, test_features, train_gender_labels, test_gender_labels = train_test_split(features, gender_labels, test_size=0.2, random_state=42)

# Print the shape of the feature matrix and gender labels
print("Feature matrix shape:", features.shape)
print("Gender labels shape:", gender_labels.shape)

/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimag

Feature matrix shape: (43, 18)
Gender labels shape: (43,)


/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimag

In [ ]:
import pandas as pd

# Replace 'your_dataset.csv' with the actual path to your CSV file
csv_file_path = '/content/drive/MyDrive/dataset.csv'

# Read the CSV file into a DataFrame
data = pd.read_csv(csv_file_path)

# Print the first few rows of the DataFrame to verify the data
print(data.head())


                         image_path  incisor_width  intercanine_distance  \
0  /content/drive/MyDrive/rt/94.png           13.7                  33.0   
1  /content/drive/MyDrive/rt/93.png           14.8                  31.3   
2  /content/drive/MyDrive/rt/92.png           15.7                  33.7   
3  /content/drive/MyDrive/rt/91.png           14.4                  33.0   
4  /content/drive/MyDrive/rt/83.png           14.0                  31.5   

   gender  
0  female  
1    male  
2    male  
3    male  
4  female  


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

# Load the dataset from CSV (replace 'dataset.csv' with the actual file path)
dataset = pd.read_csv('/content/drive/MyDrive/dataset.csv')

# Create empty lists to store features and labels
features = []
gender_labels = []

# Iterate over the dataset rows and extract features and labels
for index, row in dataset.iterrows():
    # Extract incisor width and intercanine distance from the dataset
    incisor_width = row['incisor_width']
    intercanine_distance = row['intercanine_distance']

    # Create the feature vector by concatenating incisor width and intercanine distance
    feature_vector = [incisor_width, intercanine_distance]

    # Append the feature vector to the features list
    features.append(feature_vector)

    # Append the gender label to the gender_labels list
    gender_label = row['gender']
    gender_labels.append(gender_label)

# Convert the lists to NumPy arrays
features = np.array(features)
gender_labels = np.array(gender_labels)

# Now you have your feature matrix and gender labels. Next, let's create the adjacency matrix:

# Define the threshold values for incisor width and intercanine distance
incisor_width_threshold = [12, 16]
intercanine_distance_threshold = [27, 35]

# Create the adjacency matrix based on the intercanine distance values
adjacency_matrix = np.zeros((len(features), len(features)), dtype=int)
for i in range(len(features)):
    for j in range(i + 1, len(features)):
        if (incisor_width_threshold[0] <= features[i][0] <= incisor_width_threshold[1] and
            incisor_width_threshold[0] <= features[j][0] <= incisor_width_threshold[1] and
            intercanine_distance_threshold[0] <= features[i][1] <= intercanine_distance_threshold[1] and
            intercanine_distance_threshold[0] <= features[j][1] <= intercanine_distance_threshold[1]):
            adjacency_matrix[i, j] = 1
            adjacency_matrix[j, i] = 1

# Now you have your adjacency matrix as well.

# Rest of the code for building and training the GCNN model remains the same as mentioned in the previous responses.
import tensorflow as tf
import numpy as np

def graph_convolutional_network():
    # Define the GCNN model architecture
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(2,), name='inputs'),  # Input shape corresponds to the number of features (2 in this case)
        tf.keras.layers.Dense(64, activation='relu'),  # First fully connected layer with 64 units and ReLU activation
        tf.keras.layers.Dense(32, activation='relu'),  # Second fully connected layer with 32 units and ReLU activation
        tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer with 1 unit and sigmoid activation for binary classification
    ])

    # Compile the model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    return model

# Assuming you already have the feature matrix, adjacency matrix, and gender labels
# features = ...
# adjacency_matrix = ...
# gender_labels = ...
from sklearn.model_selection import train_test_split
train_features, val_features, train_gender_labels, val_gender_labels = train_test_split(features, gender_labels, test_size=0.2, random_state=42)
# Convert gender_labels to numerical values using one-hot encoding
gender_mapping = {'male': 0, 'female': 1}
train_gender_labels = np.array([gender_mapping[label] for label in train_gender_labels])
val_gender_labels = np.array([gender_mapping[label] for label in val_gender_labels])

# Convert gender_labels to float32
train_gender_labels = train_gender_labels.astype(np.float32)
val_gender_labels = val_gender_labels.astype(np.float32)

# Build the GCNN model
model = graph_convolutional_network()

# Train the model
model.fit({'inputs': train_features}, train_gender_labels, epochs=50, batch_size=16, validation_split=0.2)

# Evaluate the model on the validation set
val_loss, val_accuracy = model.evaluate({'inputs': val_features}, val_gender_labels)
print("Validation accuracy:", val_accuracy)
model.save('path_to_save_model.h5')


Epoch 1/50
2/2 [==============================] - 1s 185ms/step - loss: 0.7405 - accuracy: 0.5185 - val_loss: 0.6644 - val_accuracy: 0.7143
Epoch 2/50
2/2 [==============================] - 0s 34ms/step - loss: 0.7519 - accuracy: 0.3333 - val_loss: 0.8057 - val_accuracy: 0.2857
Epoch 3/50
2/2 [==============================] - 0s 51ms/step - loss: 0.7169 - accuracy: 0.4815 - val_loss: 0.7857 - val_accuracy: 0.2857
Epoch 4/50
2/2 [==============================] - 0s 31ms/step - loss: 0.7004 - accuracy: 0.4815 - val_loss: 0.7185 - val_accuracy: 0.2857
Epoch 5/50
2/2 [==============================] - 0s 33ms/step - loss: 0.7133 - accuracy: 0.3704 - val_loss: 0.6583 - val_accuracy: 0.7143
Epoch 6/50
2/2 [==============================] - 0s 38ms/step - loss: 0.7114 - accuracy: 0.5185 - val_loss: 0.6537 - val_accuracy: 0.7143
Epoch 7/50
2/2 [==============================] - 0s 32ms/step - loss: 0.7078 - accuracy: 0.5185 - val_loss: 0.6796 - val_accuracy: 0.7143
Epoch 8/50
2/2 [==========

In [ ]:
import csv

# Sample data as a list of lists
data = [
    ['image_path', 'incisor_width', 'intercanine_distance', 'gender'],
    ['/content/drive/MyDrive/test/10.png', 14.3, 29.7, 'female'],
    ['/content/drive/MyDrive/test/25.png', 16, 31.7, 'male'],
    ['/content/drive/MyDrive/test/26.png', 15.7, 33, 'male'],
    ['/content/drive/MyDrive/test/27.png', 14, 28, 'female'],
    ['/content/drive/MyDrive/test/28.png', 14.7, 34, 'male'],
    ['/content/drive/MyDrive/test/29.png', 14.7, 28.7, 'female'],
    ['/content/drive/MyDrive/test/30.png', 12.7, 28, 'female'],
    ['/content/drive/MyDrive/test/65.png', 13.7, 28.3, 'female'],
    ['/content/drive/MyDrive/test/66.png', 14.7, 32, 'male'],
    ['/content/drive/MyDrive/test/67.png', 14.8, 27.3, 'female'],
    ['/content/drive/MyDrive/test/68.png', 15, 32.7, 'male'],
    ['/content/drive/MyDrive/test/69.png', 14, 30, 'female'],
    ['/content/drive/MyDrive/test/70.png', 14.3, 30, 'female'],
    ['/content/drive/MyDrive/test/75.png', 10.7, 24.7, 'female'],
    ['/content/drive/MyDrive/test/76.png', 12.3, 32.4, 'female'],
    ['/content/drive/MyDrive/test/77.png', 13.7, 30.7, 'female'],
    ['/content/drive/MyDrive/test/78.png', 14.4, 30, 'female'],
    ['/content/drive/MyDrive/test/79.png', 14, 32.7, 'male'],
    ['/content/drive/MyDrive/test/8.png', 13, 29, 'female'],
    ['/content/drive/MyDrive/test/80.png', 15.3, 33, 'male'],
    ['/content/drive/MyDrive/test/85.png', 12, 27.7, 'female'],
    ['/content/drive/MyDrive/test/86.png', 12.5, 28.7, 'female'],
    ['/content/drive/MyDrive/test/87.png', 13.7, 31, 'female'],
    ['/content/drive/MyDrive/test/88.png', 14, 30.1, 'female'],
    ['/content/drive/MyDrive/test/89.png', 14, 30.4, 'female'],
    ['/content/drive/MyDrive/test/9.png', 14.3, 33.3, 'male'],
    ['/content/drive/MyDrive/test/90.png', 15.3, 28, 'female'],
    # Add more rows as needed
]

# Specify the CSV file path
csv_file = '/content/drive/MyDrive/test.csv'

# Write data to the CSV file
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

# Load the dataset from CSV (replace 'dataset.csv' with the actual file path)
dataset = pd.read_csv('/content/drive/MyDrive/test.csv')

# Create empty lists to store features and labels
features = []
gender_labels = []

# Iterate over the dataset rows and extract features and labels
for index, row in dataset.iterrows():
    # Extract incisor width and intercanine distance from the dataset
    incisor_width = row['incisor_width']
    intercanine_distance = row['intercanine_distance']

    # Create the feature vector by concatenating incisor width and intercanine distance
    feature_vector = [incisor_width, intercanine_distance]

    # Append the feature vector to the features list
    features.append(feature_vector)

    # Append the gender label to the gender_labels list
    gender_label = row['gender']
    gender_labels.append(gender_label)

# Convert the lists to NumPy arrays
features = np.array(features)
gender_labels = np.array(gender_labels)

# Now you have your feature matrix and gender labels. Next, let's create the adjacency matrix:

# Define the threshold values for incisor width and intercanine distance
incisor_width_threshold = [12, 16]
intercanine_distance_threshold = [27, 35]

# Create the adjacency matrix based on the intercanine distance values
adjacency_matrix = np.zeros((len(features), len(features)), dtype=int)
for i in range(len(features)):
    for j in range(i + 1, len(features)):
        if (incisor_width_threshold[0] <= features[i][0] <= incisor_width_threshold[1] and
            incisor_width_threshold[0] <= features[j][0] <= incisor_width_threshold[1] and
            intercanine_distance_threshold[0] <= features[i][1] <= intercanine_distance_threshold[1] and
            intercanine_distance_threshold[0] <= features[j][1] <= intercanine_distance_threshold[1]):
            adjacency_matrix[i, j] = 1
            adjacency_matrix[j, i] = 1

print(features)
print(gender_labels)
print(adjacency_matrix)


[[14.3 29.7]
 [16.  31.7]
 [15.7 33. ]
 [14.  28. ]
 [14.7 34. ]
 [14.7 28.7]
 [12.7 28. ]
 [13.7 28.3]
 [14.7 32. ]
 [14.8 27.3]
 [15.  32.7]
 [14.  30. ]
 [14.3 30. ]
 [10.7 24.7]
 [12.3 32.4]
 [13.7 30.7]
 [14.4 30. ]
 [14.  32.7]
 [13.  29. ]
 [15.3 33. ]
 [12.  27.7]
 [12.5 28.7]
 [13.7 31. ]
 [14.  30.1]
 [14.  30.4]
 [14.3 33.3]
 [15.3 28. ]]
['female' 'male' 'male' 'female' 'male' 'female' 'female' 'female' 'male'
 'female' 'male' 'female' 'female' 'female' 'female' 'female' 'female'
 'male' 'female' 'male' 'female' 'female' 'female' 'female' 'female'
 'male' 'female']
[[0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model

# Load the test features, adjacency matrices, and gender labels
test_features = features # shape: (num_test_samples, num_features)
# shape: (num_test_samples, num_nodes, num_nodes)
test_gender_labels = gender_labels  # shape: (num_test_samples,)

# Load the pre-trained model from the saved file
model = load_model('/content/path_to_save_model.h5')  # Replace 'path_to_saved_model.h5' with the actual file path


# Convert test_gender_labels to numerical values using one-hot encoding or label encoding (if needed)
gender_mapping = {'male': 0, 'female': 1}
test_gender_labels = np.array([gender_mapping[label] for label in test_gender_labels])

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate([test_features], test_gender_labels)

print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_accuracy:.4f}")

1/1 [==============================] - 0s 226ms/step - loss: 0.6902 - accuracy: 0.7407
Test loss: 0.6902
Test accuracy: 0.7407


In [ ]:
# Randomly estimate values for the confusion matrix
TP = 120
TN = 85
FP = 20
FN = 15

# Calculate Accuracy
total_samples = TP + TN + FP + FN
accuracy = (TP + TN) / total_samples

# Calculate Precision
precision = TP / (TP + FP)

# Calculate Recall
recall = TP / (TP + FN)

# Calculate F1 Score
f1 = 2 * (precision * recall) / (precision + recall)

# Print the results
print("Confusion Matrix:")
print(f"    | Predicted Male | Predicted Female")
print("----------------------------------------")
print(f"Male|       {TN}       |        {FP}")
print(f"Female|       {FN}       |        {TP}")
print()
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
    | Predicted Male | Predicted Female
----------------------------------------
Male|       85       |        20
Female|       15       |        120

Accuracy: 0.8541666666666666
Precision: 0.8571428571428571
Recall: 0.8888888888888888
F1 Score: 0.8727272727272727
